### ISSUE TITLE
TypeError: prettyFormat is not a function

### ISSUE THREAD

**Issue by IPWright83** [synyx/jest-canvas-snapshot-serializer#5]
I just get the following error trying to use this:

```
TypeError: prettyFormat is not a function
at format (node_modules/jest-canvas-snapshot-serializer/src/canvasSnapshotSerializer.js:3:12)
      at Object.print (node_modules/jest-canvas-snapshot-serializer/src/canvasSnapshotSerializer.js:62:25)
      at printPlugin (node_modules/pretty-format/build/index.js:330:16)
      at format (node_modules/pretty-format/build/index.js:561:16)
      at __EXTERNAL_MATCHER_TRAP__ (node_modules/expect/build/index.js:386:30)
      at Object.toMatchSnapshot (node_modules/expect/build/index.js:387:15)
      at Object.<anonymous> (src/components/Plots/Scatter/Scatter/Scatter.unit.js:172:28)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:401:19)
```

I've tried manually installing `pretty-format` as a dev dependency afterwards but that didn't fix anything unfortunately.

**Comment by IPWright83** [comment]
I think https://github.com/synyx/jest-canvas-snapshot-serializer/blob/9d3e910f5be6a11a23b0e1e848dec51ea25a3cc0/src/index.js#L7 should read: `module.exports = createCanvasSnapshotSerializer(fs, path, prettyFormat.format, expect.getState);`

**Comment by IPWright83** [comment]
Ignore the last comment...

https://github.com/synyx/jest-canvas-snapshot-serializer/blob/9d3e910f5be6a11a23b0e1e848dec51ea25a3cc0/src/canvasSnapshotSerializer.js#L3

should read `return prettyFormat.format(element, {` instead
